# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/model.model.ipynb (unless otherwise specified).

__all__ = ['DialoGPTModel']

# Cell
import torch
import torch.nn as nn
import transformers

import DialoGPT.config as config

# Cell
class DialoGPTModel(nn.Module):
    def __init__(self):
        super().__init__()
        self.model = transformers.AutoModelForCausalLM.from_pretrained(config.MODEL_NAME)

    def forward(input_ids, past_key_values):
#         input_ids = past_key_values = (batch_size, sequence_length)
#         NB: The labels are shifted automatically inside the model so labels can be equal to input_ids
        out = self.model(input_ids=input_ids, past_key_values=past_key_values)
        return out