# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {"create_path": "utils.utils.ipynb",
         "DATA_PATH": "config.ipynb",
         "MODEL_PATH": "config.ipynb",
         "OUTPUT_PATH": "config.ipynb",
         "LR": "config.ipynb",
         "TRAIN_BATCH_SIZE": "config.ipynb",
         "VALID_BATCH_SIZE": "config.ipynb",
         "NUM_EPOCHS": "config.ipynb",
         "MAX_SEQ_LEN": "config.ipynb",
         "MODEL_NAME": "config.ipynb",
         "DEVICE": "config.ipynb",
         "TOKENIZER": "config.ipynb",
         "DialoGPTDataset": "dataset.dataset.ipynb",
         "df": "dataset.dataset.ipynb",
         "DialoGPTModel": "model.model.ipynb",
         "url": "download_data.ipynb",
         "Fitter": "utils.engine.ipynb",
         "DialoGPTFitter": "utils.engine.ipynb",
         "seed_everything": "utils.utils.ipynb",
         "create_loader": "utils.utils.ipynb"}

modules = ["config.py",
           "dataset/dataset.py",
           "download_data.py",
           "None.py",
           "model/model.py",
           "utils/engine.py",
           "utils/utils.py"]

doc_url = "https://Tendo.github.io/DialoGPT/"

git_url = "https://github.com/Tendo/DialoGPT/tree/master/"

def custom_doc_links(name): return None
