# AUTOGENERATED! DO NOT EDIT! File to edit: nbs/download_data.ipynb (unless otherwise specified).

__all__ = ['url']

# Cell
import os
import DialoGPT.config as config

from pathlib import Path

# Cell
url = '"https://storage.googleapis.com/kaggle-data-sets/506221/935855/bundle/archive.zip?X-Goog-Algorithm=GOOG4-RSA-SHA256&X-Goog-Credential=gcp-kaggle-com%40kaggle-161607.iam.gserviceaccount.com%2F20200928%2Fauto%2Fstorage%2Fgoog4_request&X-Goog-Date=20200928T201056Z&X-Goog-Expires=259199&X-Goog-SignedHeaders=host&X-Goog-Signature=943501579cb0ed93077dceef35442d6155640c312ad3f41c994be4eb0586a7a74c787c4d25df84892a16497f001f55c0c540fd7d0087b260669c342170a63e1c1e4f0bb03ef2e54492b787da11d6bb17c77d1fc389829b6e8be704897024dfdd6b38d63369548543d01c37b483b56b94a13128c155504bbab55b39d624b4c9b4d9267fecb9f13d5f2566682c1e783aba790130e2ad3a9e36c5ee12f26d583f833f2d35701ebb9d55ea8d8a0135d74b03c8f9b574f96634bc6361d7445185c470451a54c6d7ab6e1a5772339b750efc90fbb69838f757f7c1f824bc9efaf0f3a2c2a8fefb60ffca063cf417aa43a7157b816bb5afa9f4c7221518f0784f15b8c4"'

# Cell
os.chdir(config.DATA_PATH)
os.system(f"wget {url} -O temp.zip")
os.system("unzip temp.zip && rm temp.zip")